version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config_v3
        target: /etc/prometheus/prometheus.yml
    networks:
      - monitoring_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:11.1.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER_FILE: /run/secrets/grafana_admin_user
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_user
      - grafana_admin_password
    networks:
      - monitoring_net
      - skaldly_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=skaldly_proxy"
        - "traefik.http.routers.grafana.rule=Host(`grafana.skaldly.fr`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  node-exporter:
    image: prom/node-exporter:v1.8.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '-housekeeping_interval=10s'
    networks:
      - monitoring_net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

configs:
  prometheus_config_v3:
    file: ./prometheus.yml

secrets:
  grafana_admin_user:
    external: true
  grafana_admin_password:
    external: true

networks:
  monitoring_net:
    external: true
  skaldly_proxy:
    external: true

volumes:
  prometheus_data:
  grafana_data:
