spring.application.name=Glotrush
spring.profiles.active=dev
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# Force Spring MessageSource to use UTF-8 regardless of platform default
spring.messages.always-use-message-format=false