ALTER TABLE accounts DROP CONSTRAINT IF EXISTS accounts_status_check;
ALTER TABLE accounts ADD CONSTRAINT accounts_status_check CHECK (status IN ('ACTIVE', 'LOCKED', 'PENDING_VERIFICATION', 'SUSPENDED', 'DELETED'));
