
INSERT INTO accounts (
    id,
    email,
    password,
    first_name,
    last_name,
    username,
    role,
    status,
    auth_key,
    failed_login_attempts,
    rejected_review_count,
    is_banned_of_review,
    current_streak,
    longest_streak,
    notif_lesson_reminder,
    notif_streak_urgency,
    notif_inactivity,
    notif_weekly_goal,
    notif_review_reminder,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    '${email}',
    '${password}',
    '${first_name}',
    '${last_name}',
    'admin',
    'ADMIN',
    'ACTIVE',
    '${secret_key}',
    0,
    0,
    false,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (email) DO NOTHING;
